### ISSUE TITLE
Add node too slow (~7 minutes)

### ISSUE THREAD

**Issue by rogermichoud** [CorfuDB/CorfuDB#1045]
## Overview

When there are unresponsive servers in the layout, add node takes way too much time.

**Comment by rogermichoud** [comment]
#1026

**Comment by zalokhan** [comment]
I reproduced this scenario locally with the servers running on local JVMs (all on localhost on different ports) rather than docker containers.
The add node consistently takes ~1min 15 seconds (with existing unresponsive servers).
I believe the docker containers are running on reduced CPU and memory resources.

Closing this issue and I will continue to benchmark this scenario.
