### ISSUE TITLE
CorfuRuntime duplicate get

### ISSUE THREAD

**Issue by dahliamalkhi** [CorfuDB/CorfuDB#136]
in CorfuRuntime.connect(), what is the purpose of doing 'get()' immediately after 'fetch()'? seems redundant:

            layout = fetchLayout();
            try {
                layout.get();
                ....

**Comment by no2chem** [comment]
fetchLayout() is asynchronous, it returns a CompletableFuture<Layout>.

Connect is a synchronous call, and the caller expects that the runtime has obtained a layout before returning. The get() call blocks until the CompletableFuture is fulfilled, or throws an exception if it is completed exceptionally. 

Because of the synchronous nature of the connect() function and the asynchronous nature of fetchLayout(), the call to get() is necessary.
