### ISSUE TITLE
ClusterStatusReport not reporting the correct cluster status when nodes are down

### ISSUE THREAD

**Issue by WenbinZhu** [CorfuDB/CorfuDB#1482]
#### Steps:
1. Bootstrap a three node cluster
2. Take down node-2
3. Take down node-3
4. Wait for 60 seconds
5. Get ClusterStatusReport

#### Results:
After step 4, the ClusterStatusReport should report the clusterStatus as UNAVAILABLE, but the result is DEGRADED.

When adding another 60 seconds waiting between step 2 and step 3, the result is STABLE, while the expected result should still be UNAVAILABLE.

**Comment by zalokhan** [comment]
Root Cause:

The cluster status depends on the layout received from the cluster.
In this case, since 2 nodes are killed, the cluster cannot commit a layout marked with 2 unresponsive nodes.
The client gets a stale layout with 0 or 1 unresponsive servers marked (depending on the timing) and then concludes the cluster to be STABLE or DEGRADED.

Solution:
The cluster status query API should depend on both: the cluster's view of itself and the clients view of the cluster.
