### ISSUE TITLE
To read cant get same result on different computers

### ISSUE THREAD

**Issue by FlyingXI** [CorfuDB/CorfuDB#1529]
i run it distributed on different computers. but when i append data on computer1, i didn't read data on computer2..
i run it by following steps:
on computer1: ./corfu_server -sm 9000
on computer2: ./corfu_server m 9000
on computer1: ./corfu_add_node -c compuer1:9000 -n computer2:9000

then i run echo "hello world" | ./corfu_stream append -c localhost:9000 -i test on computer1.  i can get the result when i run ./corfu_stream read -c localhost:9000 -i test on computer1. but i get nothing when i run ./corfu_stream read -c localhost:9000 -i test on computer2.

**Comment by zalokhan** [comment]
Let's clarify your cluster creation first. You cannot use localhost:9000 on computer1 and localhost:9000 on comuter2. They need to be linked to the public/private IP addresses so that they can discover each other. Or if you still need the same machine then you should use different ports - for example, 9000 and 9001

Did your add_node cmdlet succeed? Can you share the output for the same?

**Comment by Maithem** [comment]
Re-open this if its still an issue.
