### ISSUE TITLE
Caffeine Cache Per Entry Stats

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1579]
**Question.**
Investigate whether its possible to get eviction stats per entry. For example, is it possible to register a removalListener that provides per entry stats (i.e. how long was the entry in the cache before it was evicted)

cc: @ben-manes

**Comment by Maithem** [comment]
We would like to log evictions, but logging every eviction pollutes the log, so I was wondering if its possible to only log entries that have spent X amount of time in the cache. For example, log every entry that has only spent 3 ms in the cache.

**Comment by ben-manes** [comment]
You can have a dedicated log file so it doesn't pollute the general one. You just need to configure a different file appender for a named logger. I've done that with logback when handling data feeds.

The main caveat could be expiration, because Caffeine removes them during maintenance cycles triggered by cache usage. The cache doesn't create a scheduling thread, so worst case an expired item lingers due to inactivity on the cache. That's usually okay because it means the app is idle, as activity will evict it and the stale entry isn't returned. It would mean that the listener called promptly.

I'm still not sure what the goal is of the eviction log is though. If you want to model hit rates and are afraid of poor eviction choices, we could run an access trace through the simulator to understand the workload characteristics.

**Comment by Maithem** [comment]
I see. The goal of this is to increase the probability of capturing useful logs for particular events. I have a method that tries to access an item from the cache, if this access results in a cache miss then I would like to log when was that item evicted. For example, we would like to flag events where a cache miss happens on items that entered the cache within 5 seconds, but we don't care about cache misses of items that entered the cache 30 mins ago. We assume that items that we try access have existed in the cache at some point.

**Comment by ben-manes** [comment]
Makes sense and your idea should work fine then.

Just an fyi, we have a new research paper for Middleware (Dec) on improving the eviction policy by adapting towards recency vs frequency based on the workload patterns. I can send that privately if you (or anyone) is interested. That hasn't been implemented in Caffeine yet since I'd like to try a few more advanced algorithm ideas (as we used naive hill climbing). We showed good results with biased / mixed / changing workloads.
