### ISSUE TITLE
CLI is broken

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#161]
Can't run any of the layout add stripe/add segment commands. This patch seems to be breaking it:
d1567a3d5a541338033bd1667db82d5c5123013f

@amytai Can I revert this? what did this fix exactly ?

**Comment by amytai** [comment]
If you don't have this, the cmdlets didn't work because all the arguments
were off by 1. I guess you can revert if this breaks things. Not sure what
the commands you are trying to run look like, they might have updated
syntax by now.

**Comment by slfritchie** [comment]
Amy, the problem that I've seen since joining the team and that Michael also witnessed yesterday as that the cmdlet name needed to be specified twice.  For example, see line 5 of the "Steps to reproduce" in https://github.com/CorfuDB/CorfuDB/issues/142#issue-158809573 ... `corfu_layout` appears twice.  I'd had to double the name for all bug reports using cmdlets back at that time.

With Michael's `git revert` & commit yesterday, the doubling is no longer necessary.

**Comment by slfritchie** [comment]
@Maithem I believe that #163 fixed this. Please reopen if I'm wrong.
