### ISSUE TITLE
Potential starvation when two(or more) clients access the same stream 

### ISSUE THREAD

**Issue by lixinchengdu** [CorfuDB/CorfuDB#1661]
## Overview

Suppose multiple client are writing to the same stream at full speed. This could be a common situation in some applications. For example, in Software Defined Networking (SDN), distributed SDN controllers leverage Corfu as their data store to disseminate network traffic information. All controllers write to the same Corfu Stream. If the the networking is busy, the SDN controllers may try to disseminate their quickly-updated information to the other controllers through Corfu at full speed.   

After running for a long time, all clients except one will be starved. In particular, slower clients are starved quicker. This is because slow clients need to fetch more data from the server (whereas fast clients produce more data locally), leading to more resource (e.g. CPU, Networking) consumption for syncing data and hence less resource for writing to the stream. As a result, a slow client gets slower and slower overtime and finally is starved. This situation is aggravated if reading is slow.

From my experiment, even if two clients have similar capacities, one will be starved finally. After applying some enhancement to the reading performance, the problem is largely alleviated but the performance of one client is still slowly degraded.

**Comment by Maithem** [comment]
Are you using map.put to write data?

Currently, map.put is a mutator accessor, therefore on every write it will sync (multiple reads/follow backpointers). If the application is decoupled such that the producers don't need to sync (i.e. map.blindPut), then there is no starvation issue for the producers (since there's no sync for purely mutator methods). Obviously, the consumer needs to have enough resources to keep up with all the producers.
