### ISSUE TITLE
Checkpoint Snapshot Address not persisted to Log Data

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#1814]
## Overview

CheckpointDictKey.SNAPSHOT_ADDRESS is never persisted to the LogData Metadata, in turn, this info is used by the runtime in the stream layer in two places: the fillReadQueue and processTrimmedException.

**Comment by Maithem** [comment]
The side effect seems to be only extra retries? 

Trimmed exceptions are thrown based on CheckpointDictKey.START_LOG_ADDRESS which is persisted. Also, it seems to affect that the follow back pointers will always use the global pointer address (i.e. Long.max(context.getGlobalPointer(), context.checkpointSnapshotAddress))

**Comment by WenbinZhu** [comment]
@Maithem for current code, yes. But #1734 will later use this value as an optimization, there will be a correctness if this is not set.

**Comment by Maithem** [comment]
@WenbinZhu in general, I think we should rely on the VLO version since its safer. There are edge cases where the snapshot address (i.e. global snapshot) incorrectly reflects the "stream tail". Also, I don't think this is a optimization, the stream layer should detect epoch changes and based on that It can detect gaps that have been "synced" already.
