### ISSUE TITLE
GC for StreamView is not thread-safe

### ISSUE THREAD

**Issue by lixinchengdu** [CorfuDB/CorfuDB#1887]
## Overview

StreamView GC function is implemented in AbstractQueuedStreamView which is not thread-safe. It is possible that StreamView GC function driven by a fixed schedule executor clears readCpQueue/readQueue/resolvedQueue while other threads are accessing one of these queues.

**Comment by WenbinZhu** [comment]
StreamView GC is driven by VLO, which guarantees thread-safety.

**Comment by lixinchengdu** [comment]
It could be garbage collected directly in Stream View. The code is in ViewsGarbageCollector. Maybe it is better idea to delete the direct garbage collection for Stream View.

**Comment by WenbinZhu** [comment]
Yes I think that line can be deleted

**Comment by Maithem** [comment]
Streams opened directly via the StreamView are thread-safe and that's why the ViewsGarbageCollector is able to call it directly. On the other hand, streams opened implicitly by the ObjectsView are not thread-safe. They don't need to be, because they are synchronized via the VLO stamped lock.

Also, I don't think its a good idea to delete the stream GC, because not every stream is managed by an object. Think about the transaction poller, how do we GC it's stream view? Its not an object.

**Comment by lixinchengdu** [comment]
> Streams opened directly via the StreamView are thread-safe and that's why the ViewsGarbageCollector is able to call it directly. On the other hand, streams opened implicitly by the ObjectsView are not thread-safe. They don't need to be, because they are synchronized via the VLO stamped lock.
> 
> Also, I don't think its a good idea to delete the stream GC, because not every stream is managed by an object. Think about the transaction poller, how do we GC it's stream view? Its not an object.

Thanks a good point. We should not delete direct garbage collection on StreamView. Except for gc, every stream view APIs are synchronized. Therefore, gc should also be synchronized to make streamview thread-safe.
