### ISSUE TITLE
Data checksum

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#239]
Add support for data checksum

**Comment by no2chem** [comment]
It looks like for data checksum support, we need to decide on several things:

1) Where the checksum should be validated (client/server)
2) How to implement backwards (forward) compatibility on the log unit files

I think we need to decide on where to validate the checksums first. @slfritchie designed a client-based protocol in Machi, but I believe that a server-based checksum validation would be better, since the server could scan and "scrub" bad data. Unfortunately again this means the log units would presumably need to communicate with each over to recover, but maybe we should give up the ideal of no cross-server communication.

As for checksums for data coming in from the client, this probably could be handled by encryption (#233).

**Comment by slfritchie** [comment]
I strongly disagree.  Data integrity checking should be pushed as close to the client as possible, where "client" is the code that generates the blobs that Corfu is storing.  Anything else offers more opportunities for undetectable data corruption.  Using crypto for network transport eliminates fewer sources of corruption than end-to-end, client-generated checksums.  No, we can't shield every machine from every radiation-, bug-, and whatever-else-triggered source of corruption, but we ought to set a stake in the ground that we can & will protect against a hell of a lot of them.

A local scan & scrub doesn't care where the checksums are generated.  (They could be generated from a remote source, like rsync does, if we wanted to do something like that.  I didn't want that route for Machi.)  Since it already had to send checksum metadata to clients for all read ops, that metadata is already available 100% locally for data integrity scans.

Backward compatibility of the network protocol is a separate issue, IMHO.  The wire protocol will likely change multiple times.  End-to-end checksum metadata is only one source of change.

**Comment by no2chem** [comment]
Agree on backward compatibility. 

I can see the argument for taking a data checksum generated at the client, storing that into the server, and checking that back at the client.

But shouldn't the server be verifying checksums as well? At the very least if the server tries to retrieve an entry with a failed checksum, it should notify the client. 

So let's go forward with a design where the clients generate a checksum, since we'll assume the server will require this anyway. Where should this checksum be generated and verified? Is org.corfudb.protocols.wireprotocol.LogData the right place to do it?

**Comment by slfritchie** [comment]
> But shouldn't the server be verifying checksums as well? 

On the one hand, if the server can avoid sending known junk across the wire, shouldn't it do so?  On the other hand, perhaps we always let the client verify the checksum under the assumption that the server spends less total resources sending the junk than checking the junk?  The answer is probably lies in measuring first and making policy later?

> ... org.corfudb.protocols.wireprotocol.LogData ... ?

Good question.  I've some spelunking to do.....

**Comment by slfritchie** [comment]
For (partial) background, see also https://github.com/CorfuDB/CorfuDB/wiki/Argument-for-end-to-end-data-integrity

**Comment by no2chem** [comment]
Scott, do you want to take a lead on implementing this, or should Maithem? If you do, could you give a timeline on implementation?

In terms of feature completeness, I think we need:
1) A mechanism for the client to checksum data it is sending down the wire
2) A mechanism for the logunit to store that checksum data, and send it back with each request
3) The checksum mechanisms should be flexible, so that checksums can be turned off (for performance), or different checksums could be selected (so that, in the future, error correcting codes could be used, for example). I propose CRC32 and NONE as the initial supported checksum types.

**Comment by Maithem** [comment]
@no2chem @slfritchie  I already started looking into this just today, I'll update you with a timeline by EOD.

**Comment by Maithem** [comment]
Merged. https://github.com/CorfuDB/CorfuDB/pull/270
