### ISSUE TITLE
Stream fill hole doesn't work

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#260]
The LogunitClient is constructing an incorrect message for a fillHole operation and the server is not properly handling the message, so a client can write a hole in an address that has already been written to without throwing an Overwrite exception.

**Comment by no2chem** [comment]
Well, I don't think the problem is the client can overwrite previous data via a holeFill operation, as this test (https://github.com/CorfuDB/CorfuDB/blob/599d9b1881acee1ef47eaf58d98db24d7b1b2665/src/test/java/org/corfudb/runtime/clients/LogUnitClientTest.java#L72) seems to check for that.

I think it is a problem that holeFill doesn't throw an overwrite exception when it fails, so I'll look into that.

**Comment by Maithem** [comment]
@no2chem I think a write and fill hole operation should only differ in the LogData object they are writing. I have a patch for this, I'll push it in a bit. Essentially, what I did was remove fillHole handlers on the server and re-routed that call to the write handler, because it already knows how to deal with address over write.

Also, for some weird reason the client is constructing a trim request that is being handled by the fillhost handler.

**Comment by no2chem** [comment]
Yeah, the request is a FILL_HOLE request, but it's reusing the TrimRequest data structure, which it probably shouldn't.

**Comment by Maithem** [comment]
Addressed by #263
