### ISSUE TITLE
Cache Eviction RefCount Exception

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#357]
Reported by @dahliamalkhi 

"
I have verified that when multiple threads are writing concurrently (a lot of entries) then the method of LogUnitServer.java

 public synchronized void handleEviction(LogAddress address, LogData entry, RemovalCause cause) {

Is invoked multiple times, concurrently, on the same address/entry, causing netty to panic with ‘refcnt == 0’ on the entry."

**Comment by dahliamalkhi** [comment]
@Maithem : I now know what is going on, and what is the fix.

The first time an entry is entered to the Caffeine cache is when it arrives in a WRITE request. When it is evicted, we want to invoke release().

The second time, an entry may enter the cache because it has been evicted before but it is accessed again by a client. It arrives through a read back from  disk, and it is NOT releasable.

This happens under (mildly) high concurrency load, which is what my test did: I had ten threads reading one stream concurrently, while another thread keeps filling it with entries. The cache had to be evicted while the threads are still reading it.

The fix: Mark an entry "releasable" when arriving through a WRITE request, "nonreleasable" when it is read back from disk.

I'll do it this morning, and patch #356 .

**Comment by dahliamalkhi** [comment]
Follow up:

I am not sure if it is a Caffeine problem any more. I see that StreamLog wraps the buffer it reads in Unpooled buffer for netty, so it should actually be correct.

Also, this behavior seems to surface only in the new annotationProcessor branch. So it may be a concurrency issue introduced by the new SMR object implementation (ahem, @no2chem ).

I am still trying to find the source of the concurrency bug!

**Comment by dahliamalkhi** [comment]
OK, here is a unit test that has nothing to do with Corfu, master or other branches, that I believe demonstrates that Caffeine may duplicate entry-eviction under concurrency duress. You can run it from any Java context, it has nothing to do with Corfu.

Thoughts?

[TooMuchCaffeine.java.txt](https://github.com/CorfuDB/CorfuDB/files/629877/TooMuchCaffeine.java.txt)

**Comment by ben-manes** [comment]
I haven't played with your test yet, but I have observed ForkJoinPool run a slow task multiple times. I think this is trying to help out its workers to drain the queues. So you might try changing the Caffeine executor or using CaceWriter#delete instead. If so, we can see about whether to guard against this behavior.

**Comment by ben-manes** [comment]
I tried running your test, hacking it a little to use `java.util.BitSet` instead. The failure appears to be due to accidentally synchronize around the bitmap using different locks. The `CacheWriter` may be run concurrently on different keys, so the bitmap operation is racy. That data race could have updates lost or stale values written. When I use a `synchronized (bm)` in all usages then no duplicates are detected.

**Comment by ben-manes** [comment]
[TooMuchCaffeine.java.txt](https://github.com/CorfuDB/CorfuDB/files/629947/TooMuchCaffeine.java.txt) fixed

**Comment by dahliamalkhi** [comment]
thanks for looking into this, Ben :) !

I actually just got back from a bike ride with the intention of trying exactly this, synchronizing bm, so thanks for saving me the work of doing it. 

I guess we'll keep searching for our concurrency bug inside Corfu.

**Comment by dahliamalkhi** [comment]
Update:

The latest commit fixes the buffer management race issue, which I think has been introduced into
Corfu during the introduction of the StreamLog abstraction.

The probem was as follows:

In LogUnitServer, when the Caffeine cache evicts an entry (see
LogUnitServer::handleEviction), LogUnitServer called
release() on this entry. However, when in-memory mode, the entry is still used
in the InMemoryStreamLog. By releasing it, we risk re-allocating the memory and overwriting it.

Furthermore, when Caffeine re-retrieved the entry into the cache (see
LogUnitServer::handleRetrieval), the in-memory log entry was found and returned,
but later, Caffine again evicted it, re-releasing an entry that had refCnt zero!

The fix is to let StreamLog, which is the last component that handles the entry, handle release requests explicitly. The in-memory StreamLog does nothing on release, a normal StreamLog actually releases the buffer.
