### ISSUE TITLE
Transaction logging seems to have been deleted

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#398]
It used to be the case where transactions can be logged if setTransactionLogging is set to True in the runtime, but it seems that the logic that achieves this has been removed from ObjectsView.

@no2chem It seems like the annotation processor patches removed this

**Comment by slfritchie** [comment]
Hi, Maithem.  Are you using a branch after the annotationProcessor merge and before #391?  If so, does #391 restore the logging that you're expecting?

**Comment by Maithem** [comment]
@slfritchie  hello Scott, I was referring to the transaction stream. They've been disabled after the refactor. Look at @no2chem 's comments:

https://github.com/CorfuDB/CorfuDB/blob/7c4e28962dbd7758bf70b4f33a49dfb9764a403b/test/src/test/java/org/corfudb/runtime/view/ObjectsViewTest.java#L136


Commit id:
c87cf8786698b3d47e357213241d1c64e901dd67

**Comment by no2chem** [comment]
Yeah, my fault, we should have made sure that was working before the branch was merged in. Working on a PR now to address that issue.

**Comment by Maithem** [comment]
@no2chem no worries, I already started working on this.

**Comment by Maithem** [comment]
@no2chem With the new transaction resolution, we dont write entries for transactions that aborted, so do we care about persisting aborted transactions on the transaction stream? I see why other clients might want to know which transactions that have succeeded, but why would they care about the ones that aborted?

**Comment by no2chem** [comment]
Well, since the purpose was to know about committed transactions, it doesn't seem like there's a good reason to care about aborted transactions.



On Tue, Jan 03, 2017 at 4:36pm, Maithem < notifications@github.com [notifications@github.com] > wrote:
@no2chem [https://github.com/no2chem] With the new transaction resolution, we dont write entries for transactions that aborted, so do we care about persisting aborted transactions on the transaction stream? I see why other clients might want to know which transactions that have succeeded, but why would they care about the ones that aborted?
