### ISSUE TITLE
Inconsistency of layouts in cluster

### ISSUE THREAD

**Issue by zalokhan** [CorfuDB/CorfuDB#408]
Inconsistent layouts among the layout servers.
At an instance different layout servers can have different copies of the layout with the same epoch or with different epochs.

### Scenario

Cluster of 3 nodes running layout servers on all 3 of them. (9000, 9001 and 9002)

Start the first server in single node mode.
`./corfu_server -ms 9000`
Start the second and third server.
`./corfu_server -m 9001`
`./corfu_server -m 9002`
We now edit the layout for 9000 to this.
`./corfu_layouts -c localhost:9000 edit`
```
{
  "layoutServers": [
    "localhost:9000",
    "localhost:9001"
  ],
  "sequencers": [
    "localhost:9000"
  ],
  "segments": [
    {
      "replicationMode": "CHAIN_REPLICATION",
      "start": 0,
      "end": -1,
      "stripes": [
        {
          "logServers": [
            "localhost:9000"
          ]
        }
      ]
    }
  ],
  "epoch": 0
}
```
Ideally this should be forbidden as we are submitting a new layout with the same epoch (0). But it succeeds and now 9000 and 9001 both have this new layout.

We now edit the layout again to the following:
```
{
  "layoutServers": [
    "localhost:9000",
    "localhost:9001",
    "localhost:9002"
  ],
  "sequencers": [
    "localhost:9000"
  ],
  "segments": [
    {
      "replicationMode": "CHAIN_REPLICATION",
      "start": 0,
      "end": -1,
      "stripes": [
        {
          "logServers": [
            "localhost:9000"
          ]
        }
      ]
    }
  ],
  "epoch": 1
}
```

After saving this we see that 9002 now has the new layout with epoch 1, while 9000 and 9001 still retain the layout with epoch 0.

**Comment by slfritchie** [comment]
> Ideally this should be forbidden as we are submitting a new layout with the same epoch (0).

I've also pointed out this problem.  However, as the LayoutServer's Paxos protocol has been designed, this is a feature, not a bug.  The enforcement of epoch change is currently (and intentionally) written so that this scenario is permitted.  It is an protocol bug when you write a layout in your epoch=0 example that differed from the previous epoch=0 layout.  The bug is **you**.  `{grin}`  Having said that, I believe there it's valid for an administrator's point of view to consider this a bug as you wrote in your summary.

Similarly for your 2nd half ...  the bug is also you in that you (as a protocol participant) didn't write the exact same epoch=1 layout to servers 9000 and 9001.  Perhaps you are stuck in a GC pause, and you will do it later?  `{grin}`

We know that humans are prone to error.  Avoiding both of the your problems is probably a good idea.  We probably ought to have a discussion about what's the best way to fix them.  My initial thoughts and questions are:

Problem 1: Create a new utility that's used by a human administrator to change layout safely, following LayoutServer's peculiar protocol constraints.  Should the `corfu_layouts` utility be the "safe" one for humans to use?  Or should it be a low-level, 1-machine Paxos participant only?

Problem 2: ManagementServer (or a human) could crash during phase 2 and leave the system in problem 2's state.  Should such an agent perform "read repair" in cases when all layout replicas are not unanimous?  I think so.  And should runtime.getLayoutView().fetchLayout() return a layout from quorum of identical replies?  Yes, but instead the current implementation is buggy and may return a minority layout.

**Comment by zalokhan** [comment]
You are right.
So I have a small patch to `corfu_layouts` cmdlet to make sure we increment the epoch and hence don't submit the new layout with the same epoch. This should fix it for now.

But we also need to incorporate something to prevent the user changing the epoch.
