### ISSUE TITLE
Quorum replication breaks compaction

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#562]
With quorum replication segments are no longer static because of being able to overwrite, which breaks the compaction mechanism

**Comment by kspirov** [comment]
Hi, I  am traveling currently in one of the few places in the world with almost no internet, but I will be back on Monday.

Can you give me more technical details, because I remember this change very well. Especially in order not to break compaction, one ArrayList was changed to LinkedHashMap, so overwrite  used to work as you care only about the last value.

The only issue we talked about is how to mod the threshold in order compaction to be triggered.
Is there something different?

**Comment by slfritchie** [comment]
Mid-June issues review: ping @Maithem and @kspirov

**Comment by kspirov** [comment]
Let me take it for myself.
I believe the only that is necessary here is the threshold in order to start the trim().
With other words the trim() is OK, the starting of trim() is not always ok.

**Comment by no2chem** [comment]
Let's have this done by v1.0.

**Comment by Maithem** [comment]
The compaction algorithm changed and this is no longer applicable. We will need to consider this replication mode when we re-implement garbage collection.
