### ISSUE TITLE
Trimmed addresses should be evicted from the cache

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#790]
When AddressSpaceView gets a trimmed exception, it should evict all trimmed entries from the cache.

**Comment by slfritchie** [comment]
Here's the idea that I had Friday.  I've no idea yet if it's feasible yet, but ... while #791 wishes to change cache eviction policy to bound in space, I'm wondering if it's feasible to use another Caffeine feature to perform this ticket's eviction based on **logical** time.

* The logical time would be based on Corfu log addresses that have been witnessed locally as being trimmed.  
* The clock starts at -1
* For each TrimmedException we see at address A, we advance the local logical clock to A.
* If we can push Caffeine's code to use this notion of logical time instead of wall clock time, then we should get this ticket's eviction policy "for free".

I'm also not sure yet if Caffeine's time-based eviction policy will proactively remove entries from the cache once the clock (regardless of type) advances past an expiration time.  For example, if we put 100 entries into a cache with an expiration time of T, then the whatever-style-clock ticks past time T, what actions are required to expire the 100 entries?  Does a background thread check for expiration & evict expired entries?  Is a single cache access required to trigger a scan of some/all entries?  Or do we have a worst-case of requiring access of all 100 entries to trigger expiry?

**Comment by Maithem** [comment]
Since the client cache is expected to be small why not just iterate through the keys and evict the ones that are < trim mark?

Also, caffeine's time eviction policy is not enforced actively. I believe there has to be an event (i.e. put/get) to trigger the eviction.

**Comment by ben-manes** [comment]
Caffeine's maintenance operations are amortized to minimize locking. It uses a write-ahead-log approach to batch read events and replay them under a lock on the non-concurrent algorithms. There is a state machine to manage the lock, where a write will always trigger a maintenance cycle. The details are described on this [article](http://highscalability.com/blog/2016/1/25/design-of-a-modern-cache.html) and [slide deck](https://docs.google.com/presentation/d/1NlDxyXsUG1qlVHMl4vsUUBQfAJ2c2NsFPNPr2qymIBs).

Expiration is performed in O(1) time using either time a bounded LRU queue or a timer wheel. Both require some cache activity, but not that the expired entry is accessed. The time source can be provided using a `Ticker`, primarily for [testing purposes](https://github.com/ben-manes/caffeine/wiki/Testing).

If a trimmed exception is an infrequent event then a full scan is simplest (see `asMap()` view). Otherwise your logical clock approach should be compatible, if you are careful to not mix time sources.
