### ISSUE TITLE
Incorrect Checkpoint Metadata

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#873]
The checkpoint start address (
CheckpointEntry.CheckpointDictKey.START_LOG_ADDRESS)  should be the global address of the first checkpoint record and not the version of the version locked object at the time of checkpointing.

CheckpointEntry.CheckpointDictKey.START_LOG_ADDRESS

@slfritchie why does the checkpoint data need the version locked object version persisted anyways?

**Comment by slfritchie** [comment]
@Maithem That change was made during the move of checkpoint entries to a separate stream by #669. Using this PR to trigger documentation change (at least) seems a good idea.

**Comment by no2chem** [comment]
@Maithem - It needs to be the version of the version locked object, that's critical. The field name was reused.

**Comment by Maithem** [comment]
@no2chem Well why is it critical, can you elaborate?

Also, I don't think that there are external dependencies to START_LOG_ADDRESS, so now is probably the best time to change it.

**Comment by no2chem** [comment]
We've had several discussions about this (you included) in the past. This is due to sequencer state. If you have a situation where the object is at version 5 and the snapshot is at address 10, after trim, the sequencer will still point to 5. Unless it's noted in the checkpoint record, the implementation would attempt to sync to 5 and throw TrimmedException infinitely since it doesn't know the checkpoint refers to object version 5 (the stream implementation believes it can only recover object version 10). You can attempt to change this yourself to see what happens.
