### ISSUE TITLE
Transaction aborted happens to be committed

### ISSUE THREAD

**Issue by rogermichoud** [CorfuDB/CorfuDB#974]
If there is a network exception during the chain replication write of the transaction entry, the network exception gets propagated as a transactionAbortedException. Transaction aborted should mean that the transaction was not committed.

The problem is that doesn't mean the transaction was aborted because if at least one node of the chain successfully wrote the entry, hole filling will likely propagate it to the other logUnits (if the logUnit that contains it is still part of the layout).

The Fix will block the client infinitely until it finishes its transaction. We also converged on having a parameter for debugging purpose to set a timeout.

**Comment by Maithem** [comment]
After having discussion with more people, this might not be a bug. Even though transactionAbortedException has a cause, the exception's name might convey the wrong semantics. For example, maybe TransactionError is more appropriate. Other db systems throw a similar exception and applications can deal with the stated side effect.

I think we need more information about whether applications desire these semantics, or not.

**Comment by no2chem** [comment]
It's a bug. A TransactionAbortedException should only occur if there is a transactional abort, full stop.

We are not relaxing the guarantees we provide to applications, and so far you have not provided a compelling reason to.

**Comment by Maithem** [comment]
You're conclusion is based on a false premise. Nowhere in my post does it say to "relax guarantees". 
It makes sense to throw TransactionError instead of TransactionAbortedException. 
Halting the application while attempting to guarantee the completion of an operation "forever" might not be desirable for applications, which is a plausible explanation to why other dbs decided not do provide that guarantee. Finally, I don't think that trying to complete a transaction in perpetuity makes it have "better" semantics than other dbs, that's just absurd.

**Comment by Maithem** [comment]
Retrying the operation forever also lacks generality. For example, there are other ways where the transaction can fail even after it commits and retrying doesn't fix the problem

Anyways, I think making this optional and throwing TransactionError reconciles the different views for now.

**Comment by no2chem** [comment]
Weakening the guarantees of a transaction so that the results cannot be determined (which would be the case of the TransactionError you propose), is precisely the definition of weakening semantics. Just because you don't say it explicitly doesn't mean you aren't proposing it.

False premise? The premise is in the issue report, that a network error causes a TransactionAbortedException. How can that be false?

Either the system is live and the results of the transaction can be determined, or the system is not live, and we should fatally abort the application or invoke some application handler which deals with a dead system. 

Transactions are a red herring here. The real problem is what a client should do in case the system is unresponsive. 

And no, I am opposed to TransactionError and that does NOT reconcile the issue. I don't even know what "making this optional" means. There is a bug, it needs to be fixed. It is not "optional".

**Comment by no2chem** [comment]
> Retrying the operation forever also lacks generality. For example, there are other ways where the transaction can fail even after it commits and retrying doesn't fix the problem

Really? A transaction which fails after it commits? **Please do** give an example of this, because you're digging yourself into a hole here.

**Comment by Maithem** [comment]
I'm having a technical discussion here, so I don't get the hole-digging reference.

Are you claiming that AbortCause.UNDEFINED can never be thrown even after the transaction commits (i.e. write goes through) ?

**Comment by no2chem** [comment]
It's a hole, because you're essentially claiming that the system does not actually commit transactions which it indicates are committed. That's a pretty bold claim to make, and you had better back it up with some **hard evidence**.

What does AbortCause.UNDEFINED have do with anything? Again, please back up your claim here. Your claim is that 
> the transaction can fail even after it commits

First, define _fail_. What do you mean by that? It certainly cannot "abort" after it commits, because by definition, it has committed. Fail to compute? Well, it has completed its computation by committing, so that certainly can't be the case.

**Comment by rogermichoud** [comment]
I think the proposed solution should not retry the transaction. Once the decision to commit was taken from the sequencer, there is no auto-retrying possible. After that point, there are only three possible outcomes:

1. The commit record was persisted to all the nodes. After reconfiguration, it is still persisted on all the surviving nodes.
2. The commit record was persisted to enough nodes (in chain replication, the surviving head is enough) and hole filling will propagate it to all the remaining nodes of the chain.
3. The commit record was not persisted to any surviving node and hole filling will propagate

Based on these possible outcomes, upon reconfiguration of the system (new epoch), it is very easy to verify if the transaction record was persisted or not. We will not retry anything, we will just return to the application a closure on the state of the transaction.

Now, Maithem brings a valid point. Do we want to force the application to hang while it waits to know the state of its transaction? In my mind, this is not clear yet. 

The application cannot perform any DB-related operation while it waits for its transaction outcome because the system is not ready. The only argument against blocking until we have a final decision on the transaction state is if the application is not interested in the outcome and wants to proceed with other computations with the same thread.

I would argue that an application that has this requirement should be able to build its model around it by leveraging multithreading and/or futures. The question remains, should we provide the client with hooks to do this if they want to (hence the optional) or should we let them build it around our model?

**Comment by no2chem** [comment]
To be clear, retry indefinitely here (and previously) means to retry  determing whether the tx was successful. Will answer the application part later.

**Comment by medhavidhawan** [comment]
"Transactions are a red herring here. The real problem is what a client
should do in case the system is unresponsive."

Ok how do we propose solving the unresponsive client? I will provide a
scenario from a user perspective :

A client gets partitioned in the middle of a transaction for 20 minutes.
The transaction was hole filled and and effects are showing up in all the
other clients.

Typically we want to kill this client soon so that when connectivity
returns we can start fresh. Since we are killing this client we want to
tell the user something about the transactions in flight that could be
affected. What should we tell the user ? I am deliberately not using any
technical terms to keep it very open. We need to discuss this from user
experience perspective. I am not the only or best person for this, I think
we should involve more people who have insight into what behavior user is
expecting.

**Comment by rogermichoud** [comment]
In the case of a client disconnected from the system for a certain time (timeout), the runtime needs indeed to return something, whether we are in the middle of a transaction, a read or a write (or anything else). 

If this happens, the client has no way to know what happened with the operation it was executing. We can just return a generic exception (e.g. SystemUnvailableException) and shut down the runtime. The only way the client would be able to talk back to the client is to reconnect.

When the client reconnects, it might want to know what happened with its latest operation (or not ?). Should we provide a way for the client to do this (automatically) if it wants to know?

On the flip side, I think it makes sense for the client to hang for a while (timeout) to give a chance to the system to re-converge. In the current implementation, a single networkException will return a false state.

**Comment by no2chem** [comment]
Agree here - if you throw this exception (whatever you want to call it), the client has no way to recover. It can retry the operation after reconnect, but that means the client needs to wrap everything in a retry loop - unpleasant to program with, to say the least.

We should open a new thread here. There are two problems being discussed.
First, should we throw TransactionAbortedException if the transaction is not aborted? The answer is **no**.
Second, what should we do in the case of an unresponsive system? 

I'd like to base my answer to the second question on the principle that we've stuck to so far in the design of Corfu - the client code should not be exposed to the details of the distributed system. Other than the connection string provided to the runtime, the client doesn't need to know whether the sequencer fails or the details of the replication protocol. We need to maintain that, and having a timeout exposes the client to those details.

In the scenario provided by @medhavidhawan, it seems like 

api-request>
map.get
map.put
return map.get to api

This api-request is on some http thread, no? Isn't the system already monitoring the response time of these threads (and timing out, interrupting the thread when necessary?) When the api-level timeout occurs, a timeout response is retuned to the API client, no? I don't think we need a Corfu time-out on top of that.

The killing of the client application part seems a bit odd. Why do you need to start fresh? Presumably you would have to implement some sort of loop which restarts the client app. And then how does Corfu decide whether reconfiguration is just taking a long time or the system is no longer accessible (due to partition or some other condition)? 

It seems that we do need some way to inform the client of communication failures, and for the client to set some sort of policy on what it wants to do. I suggest that we add a handler in the runtime. Something like a `registerFailureHandler()` method. The failure handler could for example communicate with some external system or wait a specific amount of time before killing the entire application, either by interrupting all threads with some special exception or really killing everything with `Application.exit()`.
